version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: ${RDS_ENDPOINT}
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: my_password
      DATABASE_NAME: names
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api